// flow-typed signature: 7e8dd33ab20ca4d1de34e5a1a1595f5e
// flow-typed version: <<STUB>>/snowpack_v^2.5.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snowpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snowpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snowpack/assets/babel-plugin' {
  declare module.exports: any;
}

declare module 'snowpack/assets/hmr' {
  declare module.exports: any;
}

declare module 'snowpack/dist-node/index.bin' {
  declare module.exports: any;
}

declare module 'snowpack/dist-node' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/commands/add-rm' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/commands/build-util' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/commands/build' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/commands/dev' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/commands/esbuildPlugin' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/commands/import-resolver' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/commands/install' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/commands/paint' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/commands/src-file-extension-mapping' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/config' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/hmr-server-engine' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/resolve-remote' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/rewrite-imports' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/rollup-plugin-catch-unresolved' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/rollup-plugin-css' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/rollup-plugin-entrypoint-alias' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/rollup-plugin-remote-cdn' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/rollup-plugin-stats' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/rollup-plugin-wrap-install-targets' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/scan-imports' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/stats-formatter' {
  declare module.exports: any;
}

declare module 'snowpack/dist-src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snowpack/assets/babel-plugin.js' {
  declare module.exports: $Exports<'snowpack/assets/babel-plugin'>;
}
declare module 'snowpack/assets/hmr.js' {
  declare module.exports: $Exports<'snowpack/assets/hmr'>;
}
declare module 'snowpack/dist-node/index.bin.js' {
  declare module.exports: $Exports<'snowpack/dist-node/index.bin'>;
}
declare module 'snowpack/dist-node/index' {
  declare module.exports: $Exports<'snowpack/dist-node'>;
}
declare module 'snowpack/dist-node/index.js' {
  declare module.exports: $Exports<'snowpack/dist-node'>;
}
declare module 'snowpack/dist-src/commands/add-rm.js' {
  declare module.exports: $Exports<'snowpack/dist-src/commands/add-rm'>;
}
declare module 'snowpack/dist-src/commands/build-util.js' {
  declare module.exports: $Exports<'snowpack/dist-src/commands/build-util'>;
}
declare module 'snowpack/dist-src/commands/build.js' {
  declare module.exports: $Exports<'snowpack/dist-src/commands/build'>;
}
declare module 'snowpack/dist-src/commands/dev.js' {
  declare module.exports: $Exports<'snowpack/dist-src/commands/dev'>;
}
declare module 'snowpack/dist-src/commands/esbuildPlugin.js' {
  declare module.exports: $Exports<'snowpack/dist-src/commands/esbuildPlugin'>;
}
declare module 'snowpack/dist-src/commands/import-resolver.js' {
  declare module.exports: $Exports<'snowpack/dist-src/commands/import-resolver'>;
}
declare module 'snowpack/dist-src/commands/install.js' {
  declare module.exports: $Exports<'snowpack/dist-src/commands/install'>;
}
declare module 'snowpack/dist-src/commands/paint.js' {
  declare module.exports: $Exports<'snowpack/dist-src/commands/paint'>;
}
declare module 'snowpack/dist-src/commands/src-file-extension-mapping.js' {
  declare module.exports: $Exports<'snowpack/dist-src/commands/src-file-extension-mapping'>;
}
declare module 'snowpack/dist-src/config.js' {
  declare module.exports: $Exports<'snowpack/dist-src/config'>;
}
declare module 'snowpack/dist-src/hmr-server-engine.js' {
  declare module.exports: $Exports<'snowpack/dist-src/hmr-server-engine'>;
}
declare module 'snowpack/dist-src/index' {
  declare module.exports: $Exports<'snowpack/dist-src'>;
}
declare module 'snowpack/dist-src/index.js' {
  declare module.exports: $Exports<'snowpack/dist-src'>;
}
declare module 'snowpack/dist-src/resolve-remote.js' {
  declare module.exports: $Exports<'snowpack/dist-src/resolve-remote'>;
}
declare module 'snowpack/dist-src/rewrite-imports.js' {
  declare module.exports: $Exports<'snowpack/dist-src/rewrite-imports'>;
}
declare module 'snowpack/dist-src/rollup-plugin-catch-unresolved.js' {
  declare module.exports: $Exports<'snowpack/dist-src/rollup-plugin-catch-unresolved'>;
}
declare module 'snowpack/dist-src/rollup-plugin-css.js' {
  declare module.exports: $Exports<'snowpack/dist-src/rollup-plugin-css'>;
}
declare module 'snowpack/dist-src/rollup-plugin-entrypoint-alias.js' {
  declare module.exports: $Exports<'snowpack/dist-src/rollup-plugin-entrypoint-alias'>;
}
declare module 'snowpack/dist-src/rollup-plugin-remote-cdn.js' {
  declare module.exports: $Exports<'snowpack/dist-src/rollup-plugin-remote-cdn'>;
}
declare module 'snowpack/dist-src/rollup-plugin-stats.js' {
  declare module.exports: $Exports<'snowpack/dist-src/rollup-plugin-stats'>;
}
declare module 'snowpack/dist-src/rollup-plugin-wrap-install-targets.js' {
  declare module.exports: $Exports<'snowpack/dist-src/rollup-plugin-wrap-install-targets'>;
}
declare module 'snowpack/dist-src/scan-imports.js' {
  declare module.exports: $Exports<'snowpack/dist-src/scan-imports'>;
}
declare module 'snowpack/dist-src/stats-formatter.js' {
  declare module.exports: $Exports<'snowpack/dist-src/stats-formatter'>;
}
declare module 'snowpack/dist-src/util.js' {
  declare module.exports: $Exports<'snowpack/dist-src/util'>;
}
